/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import dominio.Politico;
import dominio.Esperanca;

rule "Nos temos um politico honesto"
    salience 10

    when
        exists( Politico( honesto == true ) )
    then
        insertLogical( new Esperanca() );
end

rule "A esperanca vive"
    salience 10
    when
        exists( Esperanca() )
    then
        System.out.println("Hurrah!!! A democracia vive!");
end

rule "A esperanca esta morta"
    when
        not( Esperanca() )
    then
        System.out.println( "Estamos todos condenados!!! A democracia esta morta." );
end

rule "Corrompe o(s) honesto(s)"
    when
        $politico : Politico( honesto == true )
        exists( Esperanca() )
    then
        System.out.println( "Eu sou uma corporacao do mal e tenho corrompido o(a) " + $politico.getNome() );
        modify( $politico ) {
            setHonesto( false )
        }
end

